pip3 install argparse
pip3 install celery
pip3 install torch
pip3 install torchvision
pip3 install matplotlib
pip3 install pillow
pip3 install numpy
pip3 install tqdm
pip3 install flask
pip3 install flask-restful
pip3 install flask-cors
pip3 install requests
pip3 install redis
pip3 install opencv-python
pip3 install opencv-python-headless
pip3 install opencv-contrib-python
pip3 install opencv-contrib-python-headless
pip3 install opencv-python-headless