python -m pip3 install argparse
python -m pip3 install celery
python -m pip3 install torch
python -m pip3 install torchvision
python -m pip3 install matplotlib
python -m pip3 install pillow
python -m pip3 install numpy
python -m pip3 install tqdm
python -m pip3 install flask
python -m pip3 install flask-restful
python -m pip3 install flask-cors
python -m pip3 install requests
pythion -m pip3 install redis
python -m pip3 install opencv-python
python -m pip3 install opencv-python-headless
python -m pip3 install opencv-contrib-python
python -m pip3 install opencv-contrib-python-headless
python -m pip3 install opencv-python-headless